# Generated by Django 3.2.9 on 2022-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('pages', models.IntegerField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
